In [11]:
import pandas as pd
from IPython.display import HTML

In [12]:
marks = pd.read_csv("student_marks.csv")
attendance = pd.read_csv("student_attendance.csv")
marks.head()
attendance.head()

html_table = marks.to_html(index=False, justify='center')

# Step 6: Display in notebook
display(HTML(html_table))
html_table = attendance.to_html(index=False, justify='center')

# Step 6: Display in notebook
display(HTML(html_table))

In [13]:
marks.info()
attendance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
ID         3 non-null int64
Name       3 non-null object
Math       3 non-null int64
Science    3 non-null int64
dtypes: int64(3), object(1)
memory usage: 176.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
ID            3 non-null int64
Attendance    3 non-null int64
dtypes: int64(2)
memory usage: 128.0 bytes

In [14]:
merged_data = pd.merge(marks, attendance, on="ID")
merged_data

   ID   Name  Math  Science  Attendance
0   1  Rahul    80       75          90
1   2  Anita    90       88          85
2   3  Karan    70       65          88

In [15]:
merged_data.to_csv("student_complete_data.csv", index=False)

In [16]:
merged_data["Total"] = merged_data["Math"] + merged_data["Science"]
merged_data

   ID   Name  Math  Science  Attendance  Total
0   1  Rahul    80       75          90    155
1   2  Anita    90       88          85    178
2   3  Karan    70       65          88    135